name: MCore
version: '${project.version}'
main: com.canthideinbush.morawamc.mcore.MCore
api-version: 1.19
authors: [ CantHideInBush ]
depend:
  - CHIBUtils
  - WorldGuard
soft-depend:
  - PlaceholderAPI
